# Generated by Django 4.1.7 on 2023-10-16 17:34

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Public identifier')),
                ('teacher_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('student_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('duration', models.IntegerField()),
                ('words', models.JSONField()),
                ('date', models.DateTimeField()),
                ('current_percent', models.IntegerField(default=100)),
            ],
            options={
                'verbose_name': 'lesson',
                'verbose_name_plural': 'lessons',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=120, primary_key=True, serialize=False, unique=True, verbose_name='Public identifier')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('surname', models.CharField(blank=True, max_length=50)),
                ('age', models.IntegerField()),
                ('level', models.IntegerField(default=0)),
                ('teacher_id', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=120, primary_key=True, serialize=False, unique=True, verbose_name='Public identifier')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('surname', models.CharField(blank=True, max_length=50)),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Password must be at least 8 characters long and contain at least one letter and one number', regex='^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{8,}$')])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Invalid Email')])),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teachers',
            },
        ),
    ]
