# Generated by Django 4.2.6 on 2023-10-18 13:32

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Invalid Email')])),
            ],
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=120, primary_key=True, serialize=False, unique=True, verbose_name='Public identifier'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='student_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=120, verbose_name='Public identifier'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=120, verbose_name='Public identifier'),
        ),
    ]
