# Generated by Django 4.1.7 on 2023-10-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_alter_lesson_date_alter_lesson_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
