# Generated by Django 4.1.7 on 2023-10-22 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_student_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.teacher'),
        ),
    ]
