# Generated by Django 4.1.7 on 2023-10-22 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_student_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.teacher'),
        ),
    ]
